language: go
sudo: required
services:
  - docker

go:
  - 1.x

go_import_path: github.com/mchudgins/goProxy

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:  go test -v ./... && CGO_ENABLED=0 go build -o docker/goProxy main.go && sudo docker build -t mchudgins/goproxy docker && sudo docker push mchudgins/goproxy

env:
  global:
    secure: AcUsybb4zh7nJ0OJ08pYay8h5HtwmjqZvVrD6cf76yx/R0PfLr1U2rUdjVFrxW1dFkZqwWeQ7QHxoHnxsyb9Mx0YEurAfmBPLs+uFv7mRitaBhHQaVRxpANkjycmrJbL2KeaPj78/T8zFqpTSxVNn69gVPdq6vPNBiizu04FrxFUqRUux2gKKoPwS5hFjBZV11sTHP+6EkcUpDCWwNAWA77+xmlWL/RXOejXtiztVQ8iJNfnxPlN4Pr1v6yyn1FHk8BQPGUc7VIuv9
ZnPWxrGmekevVYv1vJ9Y++nYTyRAG+SDpBMVsSKZByHH+iUlgeFFq2z1iwgv3AfDYSCTX2RRvs5eig+iUQYVs+APK6RYLWirABRlFzpnnNaKLxqttzzpKN4ToWmgZmZYoYCquvxGvAJ6jzHT36M3n2Dcwdv7Eu8iah3E5BT1czS1rsnTgI+pVhfUbk1oqUfFdJi9Kjo2VfuBJVH1+zkEUoBHXg6QRFuENMw9If+yKu4xIZjRImFqfHbhpfc3BsmU79U6LFof1fAo8X0fKKyWCQ010y
xLlQTh4aZHD88pbmLXC65tlW4IJ9xLIC+OAXY2QVKmE2lPokX07NPd6R9nCnoFCnv8Z5sbJjjucIwnG3Qbia+uKHgynr/FQYhpZWE9h5DTce8eSkbicEHjhMiDMl9WifBEw=
