language: go
sudo: required
services:
  - docker

go:
  - 1.x

go_import_path: github.com/mchudgins/goProxy

script:  go test -v ./... && go build -o docker/goProxy main.go && sudo docker build -t mchudgins/goproxy docker
